name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Modify app.env file
        run: |
          echo 'ENVIRONMENT=development
                SERVER_ADDRESS=0.0.0.0:8080
                DB_DRIVER=postgres
                DB_SOURCE=${{ secrets.PROD_DB_CONNECTION }}
                MIGRATION_URL=file://db/migration
                GIN_MODE=debug' > app.env
          cat app.env

      # Publish image to Docker Hub.
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-service:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
