version: "3.9"
services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secure
      - POSTGRES_DB=campin_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgres://root:secure@db:5432/campin_db?sslmode=disable
    depends_on:
      - db
    entrypoint: [ "/app/wait-for.sh", "db:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]
volumes:
  pgdata:
