apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: k8s.io/ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: campin-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Keep-Alive,User-Agent,Cache-Control,Content-Type,Access-Control-Allow-Origin"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /search-service(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: search-service-service
                port:
                  number: 80
          - path: /manager-service(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: manager-service-service
                port:
                  number: 80
          - path: /booking-service(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: booking-service-service
                port:
                  number: 80
          - path: /payment-service(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: payment-service-service
                port:
                  number: 80
          - path: /recommendation-service(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: recommendation-service-service
                port:
                  number: 80
