basePath: search-service/v1
definitions:
  api.LocationsResponse:
    properties:
      cities:
        properties:
          data:
            items:
              properties:
                city:
                  type: string
                latitude:
                  type: number
                longitude:
                  type: number
                population:
                  type: integer
                tempC:
                  type: integer
                weather:
                  type: string
                weatherShort:
                  type: string
              type: object
            type: array
          error:
            type: string
          traceId:
            type: string
        type: object
    type: object
  api.RecommendationServicePingResponse:
    properties:
      status:
        type: string
    type: object
  db.Listing:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
host: 20.13.80.52
info:
  contact:
    email: sr8905@student.uni-lj.si
    name: Šimen Ravnik
  description: This is a search service server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: CampIn Search Service API
  version: "1.0"
paths:
  /health/live:
    get:
      consumes:
      - application/json
      description: Liveness
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.RecommendationServicePingResponse'
            type: array
      summary: Liveness
      tags:
      - Health
  /health/ready:
    get:
      consumes:
      - application/json
      description: Readiness
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Readiness
      tags:
      - Health
  /metrics:
    get:
      consumes:
      - application/json
      description: Metrics
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Metrics
      tags:
      - Metrics
  /v1/listings:
    get:
      consumes:
      - application/json
      description: Returns listing by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.Listing'
            type: array
      summary: Listings list
      tags:
      - Listings
    post:
      consumes:
      - application/json
      description: Creates a listing
      parameters:
      - in: formData
        name: created_at
        type: string
      - in: formData
        name: id
        type: integer
      - in: formData
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.Listing'
            type: array
      summary: Listings create
      tags:
      - Listings
  /v1/listings/:id:
    get:
      consumes:
      - application/json
      description: Returns listing by ID
      parameters:
      - description: Listing ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.Listing'
            type: array
      summary: Listings by ID
      tags:
      - Listings
  /v1/recommendations:
    get:
      consumes:
      - application/json
      description: Returns recommendations
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.LocationsResponse'
            type: array
      summary: Recommendations
      tags:
      - Recommendations
swagger: "2.0"
